import { Crosshair, MessageSquareText, Target, Users } from "lucide-react";
import type { ReactNode } from "react";
import type { ActionLayer } from "@/types/analysis";

const evidenceCopy = { strong: "Strong evidence", moderate: "Moderate evidence", hypothesis: "Hypothesis" } as const;

export function ActionLayerCard({ actionLayer }: { actionLayer?: ActionLayer }) {
  if (!actionLayer) return null;
  const priorityStyle = actionLayer.priority === "HIGH" ? "border-rose-400/30 bg-rose-500/10 text-rose-200" : actionLayer.priority === "MEDIUM" ? "border-amber-400/30 bg-amber-500/10 text-amber-100" : "border-slate-400/30 bg-slate-500/10 text-slate-200";
  return <section className="rounded-[2rem] border border-blue-400/25 bg-gradient-to-br from-blue-500/10 via-slate-900/90 to-slate-900/70 p-7 shadow-[0_0_0_1px_rgba(96,165,250,0.08)]" aria-labelledby="next-move-title">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-medium uppercase tracking-[0.2em] text-blue-300">Research → Insight → Decision → Action</p><h3 id="next-move-title" className="mt-3 text-2xl font-semibold text-slate-50">Your Next Move</h3><p className="mt-2 max-w-2xl text-sm leading-7 text-slate-400">The clearest evidence-based action for this account.</p></div><span className={`w-fit rounded-full border px-3 py-1.5 text-xs font-semibold tracking-[0.16em] ${priorityStyle}`}>{actionLayer.priority} PRIORITY</span></div>
    <div className="mt-6 grid gap-4 lg:grid-cols-2"><Insight title="Why this priority" icon={<Target className="size-4" />}>{actionLayer.priorityReason}</Insight><Insight title="Why now" icon={<Crosshair className="size-4" />} badge={evidenceCopy[actionLayer.whyNow.evidenceLevel]}>{actionLayer.whyNow.statement}</Insight><Insight title={`Who to contact: ${actionLayer.whoToContact.primary.role}`} icon={<Users className="size-4" />}>{actionLayer.whoToContact.primary.reason}</Insight>{actionLayer.whoToContact.secondary ? <Insight title={`Secondary: ${actionLayer.whoToContact.secondary.role}`} icon={<Users className="size-4" />}>{actionLayer.whoToContact.secondary.reason}</Insight> : null}</div>
    <div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-slate-950/35 p-4"><p className="text-sm font-medium text-slate-100">Pain to lead with</p><p className="mt-3 text-xs font-medium uppercase tracking-[0.14em] text-emerald-300">Verified fact</p><p className="mt-1 text-sm leading-6 text-slate-300">{actionLayer.painToLeadWith.verifiedFact}</p><p className="mt-4 text-xs font-medium uppercase tracking-[0.14em] text-amber-200">Sales hypothesis</p><p className="mt-1 text-sm leading-6 text-slate-300">{actionLayer.painToLeadWith.hypothesis}</p></div><div className="rounded-2xl border border-white/10 bg-slate-950/35 p-4"><p className="text-sm font-medium text-slate-100">Recommended sales angle</p><p className="mt-3 text-sm leading-7 text-slate-300">{actionLayer.recommendedSalesAngle}</p><div className="mt-5 border-t border-white/10 pt-4"><p className="text-sm font-medium text-slate-100">Best next action</p><p className="mt-2 text-sm leading-7 text-blue-100">{actionLayer.bestNextAction}</p></div></div></div>
    <div className="mt-4 rounded-2xl border border-white/10 bg-slate-950/35 p-4"><p className="flex items-center gap-2 text-sm font-medium text-slate-100"><MessageSquareText className="size-4 text-blue-300" /> Outreach starters</p><div className="mt-4 grid gap-3 lg:grid-cols-3"><Starter title="Cold email" value={actionLayer.outreachStarter.coldEmailOpening} /><Starter title="LinkedIn" value={actionLayer.outreachStarter.linkedinOpening} /><Starter title="Cold call" value={actionLayer.outreachStarter.coldCallOpener} /></div></div>
  </section>;
}

function Insight({ title, icon, badge, children }: { title: string; icon: ReactNode; badge?: string; children: ReactNode }) { return <div className="rounded-2xl border border-white/10 bg-slate-950/35 p-4"><div className="flex items-center justify-between gap-3"><p className="flex items-center gap-2 text-sm font-medium text-slate-100">{icon}{title}</p>{badge ? <span className="text-xs text-blue-200">{badge}</span> : null}</div><p className="mt-3 text-sm leading-7 text-slate-300">{children}</p></div>; }
function Starter({ title, value }: { title: string; value: string }) { return <div className="rounded-xl border border-white/10 bg-white/5 p-3"><p className="text-xs font-medium uppercase tracking-[0.14em] text-slate-500">{title}</p><p className="mt-2 text-sm leading-6 text-slate-300">{value}</p></div>; }
