"use client";

import * as React from "react";
import Link from "next/link";
import { LoaderCircle, X } from "lucide-react";

export function DemoModal({ onClose }: { onClose: () => void }) {
  const [stage, setStage] = React.useState<"start" | "loading" | "brief">("start");
  React.useEffect(() => { const escape = (event: KeyboardEvent) => event.key === "Escape" && onClose(); document.addEventListener("keydown", escape); const previous = document.body.style.overflow; document.body.style.overflow = "hidden"; return () => { document.removeEventListener("keydown", escape); document.body.style.overflow = previous; }; }, [onClose]);
  React.useEffect(() => { if (stage !== "loading") return; const timer = window.setTimeout(() => setStage("brief"), 1800); return () => window.clearTimeout(timer); }, [stage]);
  const progress = stage === "loading" ? ["Reading company website", "Identifying buying signals", "Preparing outreach brief"] : [];
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 p-4 backdrop-blur-sm" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}>
    <section role="dialog" aria-modal="true" aria-labelledby="demo-title" className="max-h-[90vh] w-full max-w-4xl overflow-y-auto rounded-[2rem] border border-white/10 bg-slate-900 p-6 shadow-2xl shadow-black/50 sm:p-8">
      <div className="flex items-start justify-between gap-4"><div><p className="text-sm font-medium uppercase tracking-[0.2em] text-blue-300">Interactive demo</p><h2 id="demo-title" className="mt-2 text-2xl font-semibold text-slate-50">SalesBrief AI workflow</h2></div><button type="button" onClick={onClose} aria-label="Close demo" className="rounded-full border border-white/10 bg-white/5 p-2 text-slate-300 transition hover:bg-white/10 focus:outline-none focus:ring-2 focus:ring-blue-400"><X className="size-5" /></button></div>
      {stage === "start" ? <div className="mt-8 rounded-2xl border border-white/10 bg-slate-950/60 p-5"><label className="text-sm text-slate-300">Prospect website<input readOnly value="https://acmestudio.com" className="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 text-slate-100 outline-none" /></label><button type="button" onClick={() => setStage("loading")} className="mt-5 rounded-full bg-blue-600 px-5 py-3 text-sm font-medium text-white transition hover:bg-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-300">Generate sales brief</button></div> : null}
      {stage === "loading" ? <div className="mt-10 flex min-h-56 flex-col items-center justify-center"><LoaderCircle className="size-9 animate-spin text-blue-400" /><div className="mt-6 space-y-3 text-sm text-slate-300">{progress.map((item, index) => <p key={item} className={index === 2 ? "text-blue-300" : ""}>{index + 1}. {item}</p>)}</div></div> : null}
      {stage === "brief" ? <div className="mt-7 space-y-5"><div className="rounded-2xl border border-white/10 bg-slate-950/60 p-5"><h3 className="text-xl font-semibold text-slate-50">Acme Studio</h3><p className="mt-3 leading-7 text-slate-300">Acme Studio is an AI-first product design agency helping B2B SaaS companies improve conversion through product strategy, UX design, and rapid prototyping.</p></div><div className="grid gap-5 md:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><h4 className="font-semibold text-slate-100">Ideal customer profile</h4><ul className="mt-3 space-y-2 text-sm text-slate-300"><li>• B2B SaaS companies</li><li>• Seed to Series B startups</li><li>• Teams redesigning onboarding or conversion flows</li></ul></div><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><h4 className="font-semibold text-slate-100">Buying signals</h4><ul className="mt-3 space-y-2 text-sm text-slate-300"><li>• Recent AI product launch</li><li>• Hiring product designers</li><li>• New conversion case studies</li></ul></div></div><div className="rounded-2xl border border-blue-500/20 bg-blue-500/10 p-5 text-sm leading-7 text-blue-100"><strong>Recommended sales angle:</strong> Position the offer around conversion-focused product storytelling and faster experimentation.</div><div className="grid gap-5 md:grid-cols-2"><Draft title="Email draft" content={"Subject: Improving Acme Studio’s outbound positioning\n\nHi Sarah,\n\nI noticed Acme Studio is increasingly positioning itself around AI-first product design and conversion-focused experiences.\n\nSalesBrief AI helps teams quickly turn prospect research into structured outreach briefs, including buying signals, positioning angles, and ready-to-use messages.\n\nWould it be useful if I sent you a sample brief based on Acme Studio?\n\nBest,\nYanis"} /><Draft title="LinkedIn draft" content="Hi Sarah — I came across Acme Studio’s recent work around AI-first product design. I built a tool that turns prospect websites into structured sales briefs with buying signals and outreach angles. Happy to send you a sample based on Acme Studio." /></div><Link href="/register" className="inline-flex rounded-full bg-blue-600 px-5 py-3 text-sm font-medium text-white transition hover:bg-blue-500">Try SalesBrief AI</Link></div> : null}
    </section></div>;
}
function Draft({ title, content }: { title: string; content: string }) { return <div className="rounded-2xl border border-white/10 bg-slate-950/60 p-5"><h4 className="font-semibold text-slate-100">{title}</h4><p className="mt-3 whitespace-pre-line text-sm leading-6 text-slate-300">{content}</p></div>; }
