type EnvKey =
  | "OPENAI_API_KEY"
  | "NEXT_PUBLIC_SUPABASE_URL"
  | "NEXT_PUBLIC_SUPABASE_ANON_KEY"
  | "SUPABASE_SERVICE_ROLE"
  | "STRIPE_SECRET_KEY"
  | "STRIPE_WEBHOOK_SECRET"
  | "STRIPE_PRICE_ID"
  | "NEXT_PUBLIC_STRIPE_STARTER_PRICE_ID"
  | "NEXT_PUBLIC_STRIPE_PRO_PRICE_ID"
  | "NEXT_PUBLIC_STRIPE_BUSINESS_PRICE_ID"
  | "NEXT_PUBLIC_SUPPORT_EMAIL"
  | "NEXT_PUBLIC_SITE_URL"
  | "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY";

const envValues = {
  OPENAI_API_KEY: process.env.OPENAI_API_KEY ?? "",
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL ?? "",
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? "",
  SUPABASE_SERVICE_ROLE: process.env.SUPABASE_SERVICE_ROLE ?? "",
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY ?? "",
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET ?? "",
  STRIPE_PRICE_ID: process.env.STRIPE_PRICE_ID ?? "",
  NEXT_PUBLIC_STRIPE_STARTER_PRICE_ID: process.env.NEXT_PUBLIC_STRIPE_STARTER_PRICE_ID ?? "",
  NEXT_PUBLIC_STRIPE_PRO_PRICE_ID: process.env.NEXT_PUBLIC_STRIPE_PRO_PRICE_ID ?? "",
  NEXT_PUBLIC_STRIPE_BUSINESS_PRICE_ID: process.env.NEXT_PUBLIC_STRIPE_BUSINESS_PRICE_ID ?? "",
  NEXT_PUBLIC_SUPPORT_EMAIL: process.env.NEXT_PUBLIC_SUPPORT_EMAIL ?? "",
  NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL ?? "",
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:
    process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY ?? "",
} satisfies Record<EnvKey, string>;

export const env = {
  ...envValues,
  isDevelopment: process.env.NODE_ENV === "development",
  isProduction: process.env.NODE_ENV === "production",
};

export function getEnv(key: EnvKey) {
  return envValues[key];
}
